src/Payments.sol, src/RateChangeQueue.sol
Added docs to make it easy to reason about the absence of off by one errors in settlement, lockup and arbitration.
=> Add docs to all settlement and lockup epochs 

Makefile, foundry.toml, src/Payments.sol, src/RateChangeQueue.sol
- Enable client to terminate rail if rail is not in debt
- Allow operator to reduce rail rate if rail is not in debt and client has enough locked funds to settle the rail upto and including the current epoch.
=> feat: enable rail terminate and allow operator to reduce rail rate if rail is not in debt

src/Payments.sol
These are basically the same function, but the latter makes it possible to unapprove the operator. We might want to think about naming here, but I think we can delete the more-specific method.
=> remove approveOperator in favor of setOperatorApproval

src/Payments.sol
=>  fix: only skip arbitration for terminated rails that are beyond their max settlement epoch

src/Payments.sol
@Stebalien This causes all sorts of issues.
For example, when a rail in settled, the account lockup changes but that changes should not reflect in the operator lockup usage as lockup usage is meant to track "future" lockup.
But we still want to use the invariant modifier during rail settlement as well.
Overall, mutating state in modifers is an anti-pattern and I see why and so want to keep it at an absolute minimum.
=> Fix bugs discovered during testing PR #1: update operator allowance in the functions and not in the modifiers

src/Payments.sol, test/PaymentsAccessControl.t.sol
@Stebalien 
- I don't think we should allow people to withdraw the rail lockup during normal settlement. It messes up all of our accounting. When you settle a rail in the normal cause of events, you can only withdraw upto and including the account lockup.
- If you want to withdraw the rail "future" lockup as well (might not be the "future" for a rail in debt) -> you should foreclose the rail and be done with it as you are essentially saying that you don't trust the client to deposit more funds anyways.
=> Fix bugs discovered during testing PR #2: Allow Rail settlement and foreclosure

test/AccountLockupSettlement.t.sol, test/OperatorApproval.t.sol, test/PaymentsAccessControl.t.sol, test/RailSettlement.t.sol
This PR removes the `INITIAL_BALANCE` constants from the following test files, as they were defined but never used:
* `AccountLockupSettlement.t.sol`
* `OperatorApproval.t.sol`
* `PaymentsAccessControl.t.sol`
* `RailSettlement.t.sol`
This cleanup reduces noise and improves test readability without affecting functionality or coverage.
=> Remove unused `INITIAL_BALANCE` constants from test contracts

src/Payments.sol
The Payments contract was failing to compile with newer versions of Foundry due to stack depth issues. The error occurred in the `_settleWithRateChanges` function where too many local variables were being used, exceeding the EVM's stack limit.
Implemented several refactoring changes to reduce stack depth and improve code organization:
1. **Added SettlementState Struct**
- Created a new struct to group related settlement variables
- Reduced number of stack variables by using memory struct
- Improved state management during settlement process
2. **Refactored _settleWithRateChanges**
- Moved from multiple local variables to using SettlementState struct
- Improved readability and reduced stack depth
- Better state management during settlement process
3. **Added _getNextSegmentBoundary …
=> refactor: reduce stack depth in Payments contract to fix compilation

src/Payments.sol, src/RateChangeQueue.sol, test/RailSettlement.t.sol, test/RateChangeQueue.t.sol
This stores the rate-change queue as a single dynamic array instead of a mapping. Given how both the EVM and FEVM work, there's no extra cost for sparse arrays but there is for mappings (especially in FEVM).
From EVM gas benchmarking, this doesn't appear to make much of a difference (and I'm really not clear on why) but it makes the queue take up fewer slots at the very least.
In the FVM, this should ensure that rate changes are stored adjacent to eachother making settlement less expensive.
=> Optimize the rate-change queue

test/RailSettlement.t.sol
- Adds an assertion in `testRailTerminationAndSettlement` to ensure `settledAmount` equals the sum of `netPayeeAmount`, `paymentFee`, and `operatorCommission`. 
- This also removes an unused variable warning.
=> Add settlement breakdown assertion and remove unused variable warning in testRailTerminationAndSettlement

src/Payments.sol, test/RailSettlement.t.sol
Changes  :
1. It allows rails without arbiters to enqueue rate changes and doesn't settle rail in `modifyRailPayment`.
2. Added a test to settle rail with rate change queue without arbitration.
Closes #15 and #77 .
=> Feat: enqueue rate changes for rails without arbiters

src/Payments.sol, test/Fees.t.sol, test/PaymentsAccessControl.t.sol, test/RailGetters.t.sol, test/RailSettlement.t.sol, test/helpers/BaseTestHelper.sol, test/helpers/PaymentsTestHelpers.sol, test/helpers/RailSettlementHelpers.sol, test/mocks/MockValidator.sol
Fixes: #107 
The following PR includes the following changes - 
- Renamed all references of "Arbitration" to "Validation" across the codebase, including the Payments contract and tests.
=> Change Arbitration to Validation

src/Payments.sol, test/PayeeFaultArbitrationBug.t.sol, test/RailSettlement.t.sol
https://github.com/FilOzone/filecoin-services-payments/pull/141 fixed the bug where client funds do not get unlocked if arbitrer settles the full duration but not the full amount i.e. reduced the requested settlement amount.
This PR fixes the other bug where arbitrer can reduce the settled duration as well. In this case, we should only unlock client funds for the duration settled by the arbitrer and not for the entire requested settlement duration.
=> fix: don't unlock client funds for the full requested settlement duration if arbitrer reduces settled duration

Makefile, tools/deploy.sh
Improves reliability and developer experience for contract deployment by ensuring scripts have correct permissions and environment variables are consistently loaded.
- Issue: permission denied
- Issue: environment variable not set even after sourcing .env
- Adds `.env` loading logic to `deploy.sh` for consistent environment variable access
- Updates Makefile with explicit `chmod` targets to ensure deploy, upgrade, and admin scripts are executable before running
- Prevents common errors after a fresh clone due to missing env vars or script permissions
=> fix: reliable deploys with env loading and script permissions

README.md
This PR adds documentation to the README describing the scenario where a client reduces an operator’s `rateAllowance` after a deal proposal but before the service provider (SP) accepts the deal. It explains the contract’s behavior, why the operation fails, and how the operator can use a one-time payment from the fixed lockup as a workaround.
- References [Issue #57](https://github.com/FilOzone/filecoin-services-payments/issues/57)
=> Document Operator Allowance Reduction Edge Case and One-Time Payment Workaround

.gitattribute, README.md, src/Payments.sol, test/DepositWithPermitAndOperatorApproval.t.sol, test/RailSettlement.t.sol, test/helpers/PaymentsTestHelpers.sol
Add `depositWithPermitAndApproveOperator` to support deposit with permit and operator approval in a single transaction.
- Features
- Added `depositWithPermitAndApproveOperator` function to combine EIP-2612 permit, deposit, and operator approval.
- Refactored: Abstracted core logic of `setOperatorApproval` and `depositWithPermit` into internal functions (`_setOperatorApproval` and `_depositWithPermit`).
- Tests
- Added tests for new function: successful deposit + approval, zero value, multiple deposits, and invalid signature failure.
- Refactored test helpers, extracted shared assertion logic.
- Docs
- Updated `README` to document `depositWithPermit`, `depositWithPermitAndApproveOperator`.
- Modified `setOperatorApproval` doc in `README` to include `maxLockupPeriod`.
All existing and new …
=> Client should be able to do (ERC-20 approval + Deposit + Operator approval) in one tx

.gitignore, README.md, docs/migration-to-foundry-v1.md
- Adds a migration guide (`docs/migration-to-foundry-v1.md`) for upgrading this project to Foundry v1.0 or later.
- The guide documents the cause and solution for contract size errors encountered during development.
- Updates the README to link to the migration guide for easy reference by anyone who encounters this issue.
- Adds file `docs/migration-to-foundry-v1.md`
- Added migration guide link to README
Closes #168
=> Add migration guide for Foundry v1.0

src/Payments.sol, test/RailSettlement.t.sol
The queue is processed in a fun way such that it prematurely pops off queue segments.  As a consequence the rail can be tricked into paying for the remainder of a partially completed segment at the next segment's rate.  While at first I thought this was confined only to zero segments it is actually a problem for both the zero and nonzero case.
The fix I've added only removes segments from the queue if they have been completely processed.
=> Zero segment bug

src/Payments.sol, test/DepositWithPermitAndOperatorApproval.t.sol, test/OperatorApproval.t.sol
This pull request introduces new functionality to the `Payments` contract for managing operator approvals and deposits, along with comprehensive test coverage for the added features. The most significant changes include adding methods to increase operator approval allowances, combining deposits with operator allowance increases, and implementing corresponding tests to ensure correctness and edge-case handling.
- Resolves #174 
* **New Method: `increaseOperatorApproval`**  
Adds the ability to increase rate and lockup allowances for an already-approved operator. This ensures that existing operator approvals can be updated without revoking and re-approving.
* **New Method: `depositWithPermitAndIncreaseOperatorApproval`**  
Combines token deposits (via EIP-2612 permits) with operator …
=> feat: add functions to increase operator approval 

Makefile
Reviewer @Chaitu-Tatipamula
When running `make` without specifying a target, the default target is the first target declared in the Makefile.
Currently the default make target is `chmod-deploy`.
I think it should be `default`.
* make `default` the default make
=> make default the default make

src/Payments.sol
Reviewer @aarshkshah1992
Solidity memory arrays cannot increase in size once allocated, but it safe to truncate them.
Because memory gas is quadratic, the cost of this copy grows quickly with the size of the array.
By truncating the array we can avoid the copy step.
* replace array copy with array truncation
* verified that without truncation at least one test fails
=> View: Truncate instead of Copy

.claude/settings.local.json, .github/workflows/coverage.yml, .gitignore, codecov.yml, foundry.toml
resolves #197 
Based on the existing coverage, the codecov % was set to 85%
The report will look like
All modified and coverable lines are covered by tests ✅
> Project coverage is 87.22%. Comparing base (e4e7dcb) to head (c88d4fc).
> ✅ All tests successful. No failed tests found.
| [Files](link) | Coverage Δ | |
|---|---|---|
| [src/Payments.sol](link) | `92.48%` | |
| [src/RateChangeQueue.sol](link) | `86.36%` | |
📊 **Coverage Summary**
- **Lines**: 87.22% (+0.00%) ✅
- **Statements**: 87.31% (+0.00%) ✅
- **Branches**: 36.23% (+0.00%) ⚠️
- **Functions**: 90.68% (+0.00%) ✅
📈 **Coverage Diff**
```diff
@@            Coverage Diff             @@
==========================================
Coverage   87.22%   87.22%
==========================================
Files           2        2
Lines …
```
=> chore: Add GA workflow for test coverage reports

.github/workflows/contract-size.yml, .github/workflows/test.yml
Reviewer @rvagg
`lint` already uses 1.2.3
* update `test` and contract size check foundry to 1.2.3
=> CI: Update Foundry

src/Payments.sol
=> feat: remove unused `hasCollectedFees ` var

src/Errors.sol, src/Payments.sol, test/AccountManagement.t.sol, test/DepositWithPermitAndOperatorApproval.t.sol, test/helpers/BaseTestHelper.sol, test/helpers/PaymentsTestHelpers.sol
This PR enables transaction relayers to submit deposit transactions on behalf of users by removing the restriction that the permit recipient must be the message sender.
- Update `Payments` contract to allow relayers to submit permit signed by a user 
- Add tests
It'll improve UX by cutting down signatures from two to one as relayer / operators can accept permit and submit on users behalf.
Demo (deployment address: `0xa883569439A2E11482197d93526d64e598089DeD`):
1. Generate permit: https://eip2612.hashchainprotocol.com/generate-permit.html
2. Submit permit value + token address + signer address at https://eip2612.hashchainprotocol.com/
Closes #146
=> feat: allow relayers to submit deposit transactions

CHANGELOG.md
Retroactively assigning a version to the Filecoin-Pay contract currently used by the FWSS deployment on Calibration network.
=> build: prep v0.5.0 version of Filecoin-Pay
