- src/Payments.sol
> split min function into a stand-alone function

- .gitignore
- src/Payments.sol
> feat: rate change fixes

- src/Payments.sol
This PR adds modifiers for validating input args to various functions .
> PR #1: feat: add modifiers for validation and use them throughout contract

- src/Payments.sol
> feat: assert that rate change queue is empty post final settlement before zeroing out the rail

- src/Payments.sol
This PR refactors both the withdrawal methods to simplify the checks they make.
> PR #2: refactor: simplify withdrawal function to remove redundant checks

- src/Payments.sol
Refactors the `modifyRailPayment` function to make it easy to reason about and handles better explicit handling for rails in various state.
**_ALSO ->_**  ensures that for terminated rails that are beyond their very last epoch -> we queue up the old rate upto that last epoch ONLY ONCE and then set the rate to zero forever.
> PR #3: refactor: better explicit handling of terminated rails, terminated and expired rails and non-terminated rails in modifyRailPayment

- src/Payments.sol
This PR finishes the set of PRs needed to land the invariant refactor.
> PR #4: Finish invariant refactor

- src/Payments.sol
My mental-model of how this worked was wrong.
Let's say the payer is 2 epochs behind on lockup and a rail has a lockup period of 10 epochs. In this case, the rail currently has an "effective" lockup of 8 epochs (the payee is guaranteed to be paid for at least 8 more epochs).
Now let's say we reduce the lockup period to 8. In this case, I'd _expect_ that the payee's guarantees wouldn't change because they currently have 8 guaranteed pay epochs. However, given that lockup is based on the "lockup last settled at" epoch, their guarantee will actually reduce to 6, which is totally unfair.
In practice, reducing the lockup period may allow us to increase the lockup settlement epoch a bit but... the extra funds will be distributed among all rails.
> Forbid lockup-period reduction when payer's account isn't settled

- src/Payments.sol
It's not perfect, but it tries to make the constraints clear. It also provides a good place to start discussing potential changes.
> docs: document the payments contract

- test/RateChangeQueue.t.sol
Tests for the rate change queue library.
> tests PR #1: rate change queue

- src/Payments.sol
- test/AccountLockupSettlement.t.sol
- test/AccountManagement.t.sol
- test/ERC1967Proxy.t.sol
- test/helpers/PaymentsTestHelpers.sol
- test/mocks/MockERC20.sol
- test/mocks/ReentrantERC20.sol
Dosent test rail settlement yet. These tests mainly focus on account creation, deposits, withdrawals, account lockup and account lockup settlement.
Also lays the groundwork for testing with test harnesses, mocks and helpers.
> tests PR #2: test harness and comprehensive tests for account management(deposit and withdraw) and account lockup and settlement

- test/PaymentsAccessControl.t.sol
Tests for access control on functions.
> tests pr #3: access control tests for functions gated by modifiers

- src/Payments.sol
- test/OperatorApproval.t.sol
- test/helpers/PaymentsTestHelpers.sol
Comprehensive tests for operator allowance tracking and one time payments.
Next will focus on the rail settlement/rate queuing/arbitration flow for terminated, non-terminated, in-debted, partially settled rails.
> tests PR #4: comprehensive tests for operator allowance tracking and one time payments

- README.md
- src/Payments.sol
This PR mostly fleshes out the README, but I've also modified some of the error messages and internal docs to use the phrase "fully funded" instead of walking about "settling lockup" because I think the former will be easier for the user to understand.
> Flesh out the README and improve some of the docs/error messages

- .github/workflows/test.yml
- .gitignore
- Makefile
- foundry.toml
- src/Payments.sol
- test/AccountLockupSettlement.t.sol
- test/Fees.t.sol
- test/OperatorApproval.t.sol
- test/RailSettlement.t.sol
- test/helpers/PaymentsTestHelpers.sol
- test/helpers/RailSettlementHelpers.sol
Implements Payments contract fees and operator commission (optional) with tests.
> feat: payment fees and operator fees

- src/Payments.sol
- test/helpers/PaymentsTestHelpers.sol
Subsumes https://github.com/FilOzone/fws-payments/pull/66.
Operator commission and payment fee should apply to one time payments as well.
> feat: operator and payment fees from one time payment as well

- src/Payments.sol
- test/AccountLockupSettlement.t.sol
- test/AccountManagement.t.sol
- test/Fees.t.sol
- test/OperatorApproval.t.sol
- test/PaymentsAccessControl.t.sol
- test/RailGetters.t.sol
- test/RailSettlement.t.sol
- test/helpers/PaymentsTestHelpers.sol
- test/helpers/RailSettlementHelpers.sol
> feat:implement operator max lockup period

- test/RailSettlement.t.sol
Fixes CI failures because of merging a test that broke CI.
> fix: rail settlement tests

- src/Payments.sol
> fix: zero out comission on rail when rail is cleared

- src/Payments.sol
- test/PayeeFaultArbitrationBug.t.sol
> fix:lockup never returned when arbitration prevents full settlement

- test/OperatorApprovalUsageLeak.t.sol
- Fixes CI failures because of the test present in `OperatorApprovalUsageLeak.t.sol`
> Fix CI failure

- src/Payments.sol
- test/RailSettlement.t.sol
> fix: do not allow rate modification or one time payments for finalised rails

- src/Payments.sol
- test/Fees.t.sol
- test/OperatorApprovalUsageLeak.t.sol
- test/PayeeFaultArbitrationBug.t.sol
- test/PaymentsEvents.t.sol
- test/RailGetters.t.sol
- test/RailSettlement.t.sol
- test/helpers/RailSettlementHelpers.sol
Introduce a network of 130000attoFIL when settling a rail.
Still investigating work required on services and SDK.
Also test for the fee itself also incoming.
> Require network fee to be paid when settling a rail

- README.md
> Termination language

- docs/payments-gas-benchmarks.md
Credit goes to @Chaitu-Tatipamula for digging up these numbers here: https://github.com/FilOzone/filecoin-services-payments/issues/127#issuecomment-3075212535
> docs: add gas benchmarks for payments contract operations

- README.md
> docs: add contributing guidelines to readme

- .github/CODEOWNERS
- .github/workflows/coverage.yml
add codeonwers in order to set up merge rules to main
> chore: add code owners & fix codecov

- .github/scripts/check-contract-size.sh
Reviewer @rvagg
Duplicates https://github.com/FilOzone/filecoin-services/pull/102 to this repo
* check for empty output dictionary
> Check Contract Size: Handle Forge Build Error

- .github/scripts/check-contract-size.sh
- README.md
- foundry.toml
Do a deep dive surgery of the README to create a comprehensive builders manual for payments contract.
>  Comprehensive Builders manual for payments contract

- src/Payments.sol
This reverts commit 7eb9650e046d4cf8c3ad8f922ada3cdff5e2b97b.
> revert: "Anyone Can settleRail (#219)"

- CHANGELOG.md
Just adding a changelog file here so we can start tracking unreleased changes and make things more transparent for end users.
I haven’t put much thought into versioning for contracts we have released already, we can figure that out in a subsequent follow-up PR, together with a better versioning strategy.
> feat: add changelog-file to filecoin-pay
